version: '3.8'
 
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MY_Capstone_project1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Update to allow empty password
    ports:
      - "3306:3306"
 
  spring-boot-app:
    image: my-spring-boot-app
    restart: always
    ports:
      - "1111:1111"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/MY_Capstone_project1?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true # Updated URL with allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - server.port=1111
    depends_on:
      - mysql
