version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
    ports:
      - "1111:1111"  # Host port : Container port
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 1111
      APPLICATION_BASE_URL: http://35.177.64.228:1111
    restart: always
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"  # Host port : Container port
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password here
      MYSQL_DATABASE: my_database
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
